Correcion menunav a products
Pudin-con-pasas-uwu/ecomerce3 pull request #22
Opened 2023-04-10 22:42 UTC by kareng13

Se corrige detalle en el menunav, ya que los products no iban concorde a las categories

2023-04-10 23:12 UTC, lokilaufeysonXD approved these changes

2023-04-12 23:00 UTC, Creaky27 approved these changes
Dice que hay conflictos, pero lo aprobó Vercel jajajja...

2023-04-13 05:34 UTC, GerardoCasC requested changes
Ya funciona correctamente, solo falta agregarle responsive a las cartas de los productos

2023-04-13 07:36 UTC, lokilaufeysonXD approved these changes

2023-04-13 15:43 UTC, GerardoCasC approved these changes
Ya es responsive

2023-04-13 21:02 UTC, EdgarPerez07 approved these changes

2023-04-13 21:12 UTC, Pudin-con-pasas-uwu approved these changes

2023-04-13 23:16 UTC, merged